### ISSUE TITLE
quatToEulerVec is different from EulerVecToQuat, etc

### ISSUE THREAD

**Issue by ZhaomingXie** [raisimTech/raisimLib#159]
for quatToEulerVec, the definition is this 
inline void quatToEulerVec(const double* quat, double* eulerVec)

However, for other similar functions, the definition looks like this:
inline void eulerVecToQuat(const Vec<3>& eulerVec, Vec<4>& quat).

Why does one use double* while others use Vec<n>?

It will be great if the convention is consistent.

Thanks!

**Comment by jhwangbo** [comment]
The reason for the inconsistency is our definition of the GC. because a quaternion is embedded in the GC, you usually don't have ``Vec<4>`` instance. You can call the function like ``quatToEulerVec(gc.ptr()+3, eulerVec)``. If you have a ``Vec<4>`` instance, you can also call it ``quatToEulerVec(quat.ptr(), eulerVec)``
