### ISSUE TITLE
Limit max joint velocity

### ISSUE THREAD

**Issue by luigicampanaro** [raisimTech/raisimLib#244]
Hi,

is it possible adding a function to set the maximum velocity that the motors can exert?  

I'm mostly interested to including it in `Environment.hpp` and limit exploration  outside the motors' capabilities.

Best,
Luigi

**Comment by jhwangbo** [comment]
Velocity limit dynamics are very system-dependent. If I implement a model, it will be very inaccurate for your system. If you want to limit the exploration beyond the velocity limit, you can use termination or reward terms.

**Comment by luigicampanaro** [comment]
Thank you for replying! 
Unfortunately I wasn't very successful with both termination criteria and reward terms, and with @gsiddhant we were considering to limit motors' velocity.
But if you don't think it's appropriate, I'll discuss with him in the following days what action to take. Thanks again though

**Comment by luigicampanaro** [comment]
Also,  we are using a custom PD controller and the joint velocity limits that Raisim uses from the URDF no longer works, since we directly set the generalised forces.

**Comment by jhwangbo** [comment]
I didn't get what you meant here "joint velocity limits that RaiSim uses". There are no joint velocity limits in RaiSim. 
You should design a module that maps your torque command to the actual torque using motor dynamics. You can use motor dynamics for that.

**Comment by gsiddhant** [comment]
Hi Jemin,

Thanks for your efforts. I believe the previous comments weren't quite clear. We use custom actuation models (such as delayed PD controllers and actuator networks) to generate effective joint torques applied using `setGeneralizedForce()`. While your suggestion is perfectly valid, that is, we could map our torque command to actual torque using motor dynamics, I think it would be quite helpful and straightforward to have `setJointVelocityLimits()` such that RaiSim itself restricts joint motion beyond a velocity limit. This allows us to quickly switch between different actuation models. 

This is relevant since most of the actuation models do not account for the joint velocity limits.

I'm not sure how easy it would be to introduce the `setJointVelocityLimits()` feature in RaiSim but if you believe this will require significant work to implement, we can always perform the torque mapping to get the motors to behave within the velocity limits. 

Thanks!

**Comment by jhwangbo** [comment]
I'll think about a proper way to implement it. One possible method is to implement it as a contact problem. So this constraint aplies impulse to keep the joint velocity within the limits. Let me know what you think

**Comment by gsiddhant** [comment]
That sounds like a potential solution but does that imply the contact constraints are evaluated at each step for every feasible contact? Wouldn’t that significantly affect the efficiency of the simulator? On the other hand, would it be possible to simply clip the joint velocities while integrating the physics? Or would that break the simulator?

**Comment by jhwangbo** [comment]
The contact constraint is evaluated only when it is violated. If we just clip the velocity, you will see large contact penetrations

**Comment by gsiddhant** [comment]
I see. Thanks for letting us know. If I may ask, have you looked into this already and do you have an estimate of time required to implement? This is just to plan futurw work and experiments. Greatly appreciate the help on this!

**Comment by jhwangbo** [comment]
I think I can do the revolute and prismatic joint limits next week. ball joints are always trick but I'll try to finish it as well

**Comment by jhwangbo** [comment]
can you pull and check? Let me know if there is any degradation in performance or instability issues

**Comment by luigicampanaro** [comment]
Thanks a lot, I'll try it out and keep you posted!

**Comment by jhwangbo** [comment]
update #250
This should work much better

**Comment by luigicampanaro** [comment]
Great, thank you! :) I was testing the previous one and the difference was already visible. I'll pull again and keep you posted
