### ISSUE TITLE
ImportError: No module named raisimGymTorch.env.bin when running RaisimGymTorch

### ISSUE THREAD

**Issue by shuoli-robotics** [raisimTech/raisimLib#26]
Hi there,

Thanks for your work and license. I can successfully run the examples provided in the repo.

However, when I tested RaisimGymTorch, an error came out. So, I have a few questions about raisimGymTorch to ask:

1)  Do I have to run `python setup.py develop` using Python 2? Because when I used Python 3, I had the error `undefined symbol: _Py_ZeroStruct`

2) When I run everything with Python 2 and run `python raisimGymTorch/env/envs/rsg_anymal/runner.py`, I got the error 

```
Traceback (most recent call last):
  File "/home/shuo/raiSim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 4, in <module>
    from raisimGymTorch.env.bin import rsg_anymal
ImportError: No module named raisimGymTorch.env.bin
```
I tried to append the package's path in the code but still got the error. 

Could you please let me know how should I fix this?

Best,
Shuo

**Comment by jhwangbo** [comment]
This is probably due to the python version. Can you try it again with conda or virtualenv and python 3.5 or above?

**Comment by jhwangbo** [comment]
Your python version in ``python setup develop`` should be the same as the version that you use to run ``python runner.py``. The pybind11 builds a version-specific binary. This is the reason that python 2 doesn't work. I am not sure about the first error in your case but there are many people getting that error because of python versions (e.g., https://stackoverflow.com/questions/44737063/cython-bbox-so-undefined-symbol-py-zerostruct). That's why it's safer to use ``conda`` or ``virtualenv`` because they only have one python version (as far as I know).

**Comment by shuoli-robotics** [comment]
Hi Jemin,

Thanks for your advice! It is the Python version problem. I started to use conda from the first step and the problem was solved. Thanks!

I have another question: I tried the raisimPytorch example and saw an Anymal B which was different from the Gifs on the instruction. Is it right? 

Best,
Shuo

**Comment by jhwangbo** [comment]
Yes, I only provide the simplest example. The Gif version is not published
