### ISSUE TITLE
Friction coefficient set in the xml does not match the simulation exactly

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#55]
It seems that the friction coefficients set in the xml does not match the simulation exactly: in the source code attached, for a box of 1 kg mass, (0,0,-9.81) gravity and 0.5 friction coefficient. If an external force of (4.9,0,0) N is applied to the object. It should not move, as it is smaller than 1 * 9.81 * 0.5 = 4.905 N.  However, it moves in the simulation. Interestingly, if I set the external force to be (4.85, 0, 0) N. It completely stopped moving. Is this an expected behavior? Here is the source code: 
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/5973005/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
I could reproduce this error. I quickly looked at it but couldn't find the issue. There are a few approximations for numerical stability.  I'll check which one is causing this discrepancy. This issue is known (https://leggedrobotics.github.io/SimBenchmark/rolling/index.html) but I didn't spend time to investigate it. I'll take a deeper look at it next week.

BTW, the first argument for `setExternalForce` is the local index. and local index for all `SingleBodyObject` is zero. The method will actually ignore the first argument. So you don't have to get the index to apply the force.

**Comment by weixuanzhang** [comment]
> BTW, the first argument for `setExternalForce` is the local index. and local index for all `SingleBodyObject` is zero. The method will actually ignore the first argument. So you don't have to get the index to apply the force.
 
Thanks for the heads-up!

**Comment by jhwangbo** [comment]
This is due to the model used in RaiSim. Unfortunately, there is no perfect model for contacts. They all have pros and cons. I can point you to the literature on this matter but this will be a lot of reading. The bottom line is that this is an expected result.
