### ISSUE TITLE
spring_mount in URDF convention

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#61]
Is it possible to explain a bit more on the definition of spring_mount in URDF convention introduced here: https://raisim.com/sections/ArticulatedSystem.html Is this a quaternion describing the orientation of the spring-damper system defined in the <dynamics> tag? If so, does "1 0 0 0" align with the child frame? Thanks!
PS, it seems that the search function on the documentation website always hangs at Searching... (tested using Firefox and Chrome on Ubuntu 18.04)

**Comment by jhwangbo** [comment]
"1 0 0 0" will align with the joint frame on the parent's body. Spring element on a ball joint is confusing because there is not a real-life example. The spring force is proportional to the rotation vector (child orientation w.r.t. the spring_mount)

I'll check the website. I also experience the same issue

**Comment by jhwangbo** [comment]
I have to merge this https://github.com/readthedocs/sphinx_rtd_theme/pull/346

**Comment by jhwangbo** [comment]
it should work now. I updated the website theme file. Let me know if you find any bug

**Comment by weixuanzhang** [comment]
Alright. Thanks!
