### ISSUE TITLE
Color tag in urdf files

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#78]
So far it seems that the simulator ignores the color tag in urdf files (also mentioned in #17). Is there a plan to add this functionality?  Thanks!

**Comment by jhwangbo** [comment]
This is relatively easy to do. I will try it today

**Comment by jhwangbo** [comment]
I tried to figure out a nice way to do this. But it is not so simple. Currently, RaiSimUnity reads material from mesh files. If there is a color tag, I have to make a decision if I use the material from the mesh file or the urdf tag. I tried to give a preference to the urdf tag (which means to use the urdf tag if it is defined) but this makes many robot examples in RaiSim textureless because the nice textures are defined in the mesh files, not in the urdf tags.

I don't see a clean way to solve this problem. If you want to recolor your mesh, you can do that in the mesh file (using blender) until I find a solution.

**Comment by weixuanzhang** [comment]
Okay. Thanks for the update! I will use blender first.

**Comment by jhwangbo** [comment]
Now color tags should work. Some users have to correct their URDF but it seems like a much better way. Now color tags will override materials in mesh files.
